# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
 -  repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: name-tests-test # Verify that test files are named correctly
      - id: pretty-format-json # Set a standard for formatting JSON files
        args: ["--autofix", "--no-sort-keys"]
      - id: requirements-txt-fixer # Sort entries in requirements.txt

 - repo: https://github.com/PyCQA/isort
   rev: 5.8.0
   hooks:
      - id: isort

 - repo: https://github.com/psf/black
   rev: 21.5b2
   hooks:
      - id: black

 - repo: https://gitlab.com/PyCQA/flake8
   rev: 3.9.2
   hooks:
      - id: flake8

 - repo: https://github.com/pycqa/pydocstyle
   rev: 6.1.1  # pick a git hash / tag to point to
   hooks:
      - id: pydocstyle
        args:
          - --convention=google
        exclude: ^tests/

 - repo: https://github.com/terrencepreilly/darglint
   rev: v1.8.0
   hooks:
      - id: darglint
        args:
          - -v 2
        exclude: ^tests/
