language: python

services:
  - docker
  
addons:
  apt:
    packages:
      - docker-ce


before_install:
  - docker build -t greynsights -f docker-images/base/Dockerfile .
  - docker run greynsights

script:
  - ls
  - python3 setup.py install
  - pytest .
