language: python
python:
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - sudo apt-get update
  - sudo apt-get install libstdc++6
  - pip install -r requirements.txt
  - python3 setup.py install
# command to run tests
script:
  - pytest 
