language: python
python:
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-4.9
  - sudo apt-get upgrade libstdc++6
  - pip install -r requirements.txt
  - python3 setup.py install
# command to run tests
script:
  - pytest 
