owner_name: Bob
dataset_name: Sample Data
privacy_budget: 10.0
trusted_aggregator: None
secret_sharing: Shamirs_scheme

private_columns: None
visible_columns: default
restricted_columns: default

allowed_queries: default
visible_queries:
      - sum
      - count
      - mean
      - percentile
      - max
      - min
      - median
restricted_queries: None
